version: '3.8'

services:
  mongodb:
    image: mongo:6.0.11
    container_name: mongodb
    # command: ["--auth"]
    volumes:
      # - mongodata:/data/db
      ## 要先在電腦建立對應的資料夾
      - ~/Documents/docker-data/mongo/data/configdb:/data/configdb
      - ~/Documents/docker-data/mongo/data/db:/data/db
    networks:
      - default
    restart: always
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:${IMAGE_TAG}
    container_name: backend
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - default
    ports:
      - "3000:3000"
    # command: yarn start:prod
    restart: always
networks:
    ## 要先用docker network create一個共用網路
  default:
    external: true
    name: docker-data_default
